# Generated by Django 4.0.6 on 2022-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=10)),
                ('appointmentid', models.IntegerField(unique=True)),
                ('nameoncard', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=16)),
                ('expirymonth', models.DateField()),
                ('expiryyear', models.DateField()),
                ('cvv', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('patientid', models.IntegerField()),
                ('doctorid', models.IntegerField()),
                ('doctorname', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('patientname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('appointmentdate', models.DateField()),
                ('appointmenttime', models.CharField(choices=[('09:30-10:00 AM', '09:30-10:00 AM'), ('10:00-10:30 AM', '10:00-10:30 AM'), ('10:30-11:00 AM', '10:30-11:00 AM'), ('11:00-11:30 AM', '11:00-11:30 AM'), ('11:30-12:00 AM', '11:30-12:00 AM'), ('01:00-01:30 PM', '01:00-01:30 PM'), ('01:30-02:00 PM', '01:30-02:00 PM'), ('02:00-02:30 PM', '02:00-02:30 PM'), ('02:30-03:00 PM', '02:30-03:00 PM'), ('03:00-03:30 PM', '03:00-03:30 PM'), ('03:30-04:00 PM', '03:30-04:00 PM'), ('04:00-04:30 PM', '04:00-04:30 PM'), ('04:30-05:00 PM', '04:30-05:00 PM'), ('05:00-05:30 PM', '05:00-05:30 PM'), ('05:30-06:00 PM', '05:30-06:00 PM'), ('06:00-06:30 PM', '06:00-06:30 PM')], max_length=30)),
                ('symptoms', models.CharField(max_length=200)),
            ],
        ),
    ]
