# Generated by Django 4.0.6 on 2022-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expirymonth',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiryyear',
            field=models.CharField(max_length=6),
        ),
    ]
