# Generated by Django 4.0.6 on 2022-09-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_payment_expirymonth_alter_payment_expiryyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='username',
        ),
    ]
